In [25]:
from datetime import datetime
import math
from utils import AigSet
from imap_engine import EngineIMAP
from env_v6 import Env
import os
import numpy as np

In [26]:
s = math.sqrt
U = np.array([
    [-1/s(2),-1/s(2)],
    [1/s(2),-1/s(2)],
])
S = np.array([
    [s(3),0,0],
    [0,1,0]
])
V = np.array([
    [1/s(6),1/s(2),1/s(3)],
    [-2/s(6),0,1/s(3)],
    [1/s(6),-1/s(2),1/s(3)]
])
ans = U@S@(V.transpose())
ans = ans.astype(np.float16)
print(ans)

[[-1.  1. -0.]
 [ 0. -1.  1.]]


In [28]:
p = np.array([
    [1,0,0,0],
    [1,1,0,1],
    [0,0,-1,-1],
    [0,0,-1,1]
])
j = np.array([
    [1,0,0,0],
    [0,2,0,0],
    [0,0,2,1],
    [0,0,0,2]
])
p_ = np.linalg.inv(p)
p_@j@p

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 1. ,  2. , -0.5,  0.5],
       [ 0. ,  0. ,  2.5, -0.5],
       [ 0. ,  0. ,  0.5,  1.5]])

In [ ]:
b = np.array([
    [0,2],
    [1,0],
    [0,1],
])
c = np.array([
    [1,0,2],
    [0,1,0]
])
np.matmul(b,c)

array([[0, 2, 0],
       [1, 0, 2],
       [0, 1, 0]])

In [ ]:
bl = np.array([
    [0,1,0],
    [2/5,0,1/5]
])
bl@b

array([[1., 0.],
       [0., 1.]])

In [ ]:
cr = np.array([
    [1/5,0],
    [0,1],
    [2/5,0],
])
c@cr

array([[1., 0.],
       [0., 1.]])

In [ ]:
cr@bl

array([[0. , 0.2, 0. ],
       [0.4, 0. , 0.2],
       [0. , 0.4, 0. ]])

In [ ]:
# aigSet = AigSet('s','m')
# for aig in aigSet.aigs:
#     env = Env(aig)
#     print()
#     with open('aiginit.csv','a') as f:
#         aig = os.path.basename(aig)
#         f.write(f'{aig},{env._initNumAnd},{env._initLev}\n')
